#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Listen on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)
# 	   curl http://34.198.248.145/   --> returns string "Hello World"
#	   curl http://34.198.248.145/   --> returns header info

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
echo "Hello World!" | sudo tee /var/www/html/index*html

# testing nginx configurations
sudo nginx -t
sudo service nginx reload
