#!/usr/bin/env bash
# Replace a line with multiple lines with sed
# Performing a 301 moved permanently.
# Perform nginx server install and config

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

# configure nginx server
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/husamrio permanent;"

## Update default site to redirect and start nginx server

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
