#!/usr/bin/env bash
# Distribute requests using a roundrobin algorithm
# Configure HAProxy to send traffic to web-01 and web-02 server
# - Enables management via the init script.
# - Installs HAProxy with the following configurations:
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy


cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend greensmartsolutions.tech
    timeout client  30000
    bind 0:80
    default_backend swiftsmart


backend swiftsmart
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 224091-web-01 54.173.80.121:80 check
    server 224091-web-02 54.166.167.28:80 check
EOT

sudo service haproxy restart

