#!/usr/bin/env bash
# Creates MySQL dump of all databases
# ***********************************
# Generates compressed tar.gz archive for backup

mysqldump -u root -p"$1" --all-databases > backup.sql
tar -czvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
