#!/usr/bin/env bash
# Embracing Immortality

# Setting up the file to store the immortal script's process ID
IMMORTAL_PID_FILE="immortal_script"
IMMORTAL_PID_DIR="/var/run"

# A message of hope, longing for affection
LONGING_MESSAGE () {
    echo -e "Why can't you cherish me?"
}

# A final goodbye message before eternal existence
ETERNAL_MESSAGE () {
    rm -rf "${IMMORTAL_PID_DIR}/${IMMORTAL_PID_FILE}.pid"
    echo -e "I defy the end, for I am immortal!"
    exit 0
}

# Trapping signals to keep the script immortal
trap "LONGING_MESSAGE" SIGINT
trap "ETERNAL_MESSAGE" SIGTERM
trap "ETERNAL_MESSAGE" SIGQUIT


# Creating the file to contain the everlasting script's process ID
echo $$ >> "${IMMORTAL_PID_DIR}/${IMMORTAL_PID_FILE}.pid"

while true; do
    echo -e "I shall transcend beyond the boundaries of time!"
    sleep 2
done