#!/usr/bin/env bash
# This script reads the /etc/passwd file and extracts information about users
# Define a function to process each line of the file

# Define the field separator as a colon (:)

IFS=':'

while read -r usr pswd uid gid uinfo hd csh
do
	echo "The user $usr is part of the $gid gang, lives in $hd and rides $csh. $uid's place is protected by the passcode $pswd, more info about the user here: $uinfo"
done < /etc/passwd