#!/usr/bin/env bash
# "bad luck from Japan" the 9th, and "bad luck from Italy" the 17th

i=1
while [ "$i" -le 20 ]; do
	case "$i" in
		4)
			echo -e "$i"
			echo -e "bad luck from China"
			;;
		9)
			echo -e "$i"
                        echo -e "bad luck from Japan"
                        ;;
		17)
			echo -e "$i"
                        echo -e "bad luck from Italy"
                        ;;
		*)
			echo -e "$i"
			;;
	esac

	i=$((i+1))

done