#!/usr/bin/env bash
# Journey through the day

current_hour=0
while [ "$current_hour" -le 12 ]; do
    echo "Current hour: $current_hour"
    ((current_hour++))

    current_minute=1
    while [ "$current_minute" -le 59 ]; do
        echo "Current minute in the hour: $current_minute"
        ((current_minute++))
    done
done
