#!/usr/bin/env bash
# Checking the status of the school file

FILE="school"

if [ -e "$FILE" ]; then
    echo "school file exists."
    [[ -s "$FILE" ]] && echo "The school file is not empty."
    [[ ! -s "$FILE" ]] && echo "The school file is empty."
    [[ -f "$FILE" ]] && echo "The school is a regular file."
else
    echo "The school file does not exist."
fi
